name = "rolldorado-app-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-app.pt"
HMAC_KEY = "6e7528ea2015938be8984e3a5ff78266ddc38cdac3ef07e51cb21c2c4415575d"
COOKIE_NAME = "hjj"
PLAY_PATH = "play-now"
BUTTON_ID = "p9dbdf717a5698acf10b0b5fdf3c6095a"
GATE_SALT = "d7711aaea52da21c"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "5dmm"
CTA_SELECTOR = ".play-button"
